# CI & CD workflow
name: CI/CD - Liquid.Adapter.AzureStorage component for Liquid Application Framework

on:
  push:
    branches: [ main, releases/v2.X.X, releases/v6.X.X ]
    paths:
    - 'src/Liquid.Adapter.AzureStorage/**'
    
  pull_request:
    branches: [ main, releases/** ]
    types: [opened, synchronize, reopened]
    paths:
    - 'src/Liquid.Adapter.AzureStorage/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-reusable-build-workflow:
    uses: Avanade/Liquid-Application-Framework/.github/workflows/base-liquid-ci-and-cd.yml@main
    with:
      component_name: Liquid.Adapter.AzureStorage
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN_STORAGE }}
      nuget_token: ${{ secrets.PUBLISH_TO_NUGET_ORG }}
